//! Routing-table `MessagePack` forward-compat check.
//!
//! `docs/15-compatibility.md` requires that routing-table encoding stays
//! additive: existing decoders must always succeed against tables produced
//! by older builds. The fixture in [`GOLDEN_V1`] was produced by the original
//! Phase 4A `RoutingTable::to_msgpack` and is regenerated only on a deliberate
//! schema bump (see `tests/regenerate_fixture` below — gated behind an
//! environment variable so it cannot regenerate accidentally).
//!
//! `xtask schema-check` runs this single test to verify the contract.

#![allow(clippy::items_after_statements)] // tests favour locality over hoisting

use kamino_cluster::RoutingTable;
use kamino_core::hasher::XxHasher;
use kamino_core::ids::MemberId;
use kamino_core::member::Member;
use std::net::{IpAddr, Ipv4Addr, SocketAddr};

include!("fixtures/routing_v1.rs");

#[test]
fn current_code_decodes_v1_fixture() {
    let rt = RoutingTable::from_msgpack(GOLDEN_V1).expect("decode v1 golden fixture");

    assert_eq!(
        rt.schema_version, 1,
        "schema_version must be readable from v1 fixture",
    );
    assert_eq!(rt.signature, FIXTURE_SIGNATURE);
    assert_eq!(rt.members.len(), FIXTURE_MEMBER_COUNT);
    assert_eq!(
        rt.partition_count(),
        FIXTURE_PARTITION_COUNT,
        "every partition primary must round-trip",
    );

    // Spot-check: the first partition's primary must still be a known member.
    let first_primary = rt.primary_for(0).expect("primary for partition 0");
    assert!(rt.members.contains(first_primary));
}

#[test]
fn regenerate_fixture_documented() {
    // Hidden under an env var so we don't accidentally rewrite the golden
    // bytes. Set `KAMINO_REGEN_ROUTING_FIXTURE=1` and run this test in a
    // clean checkout to refresh `routing_fixture_v1.in.rs`.
    if std::env::var("KAMINO_REGEN_ROUTING_FIXTURE")
        .ok()
        .as_deref()
        != Some("1")
    {
        return;
    }

    let mk = |id: u64, port: u16| {
        Member::new(
            MemberId::from_raw(id),
            format!("n{id}"),
            SocketAddr::new(IpAddr::V4(Ipv4Addr::LOCALHOST), port),
            SocketAddr::new(IpAddr::V4(Ipv4Addr::LOCALHOST), port + 2),
            // Deterministic birthdates.
            1_000_000 + id,
        )
    };
    let members = vec![mk(1, 3320), mk(2, 3322), mk(3, 3324)];
    let rt = RoutingTable::build(members, &XxHasher, 271, 20, 1.25, 2, FIXTURE_SIGNATURE).unwrap();
    let bytes = rt.to_msgpack().unwrap();

    let path = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("tests")
        .join("fixtures")
        .join("routing_v1.rs");
    let body = render_fixture(&bytes);
    std::fs::write(&path, body).expect("write fixture");
    eprintln!("wrote {} ({} bytes)", path.display(), bytes.len());
}

#[allow(dead_code)] // only used when the env-var-gated regenerator runs
fn render_fixture(bytes: &[u8]) -> String {
    let mut s = String::new();
    s.push_str("// Generated by routing_schema_forward_compat.rs::regenerate_fixture\n");
    s.push_str("// Do not edit by hand — set KAMINO_REGEN_ROUTING_FIXTURE=1 to refresh.\n\n");
    s.push_str("const FIXTURE_SIGNATURE: u64 = 42;\n");
    s.push_str("const FIXTURE_MEMBER_COUNT: usize = 3;\n");
    s.push_str("const FIXTURE_PARTITION_COUNT: u32 = 271;\n");
    s.push_str("const GOLDEN_V1: &[u8] = &[\n");
    const PER_LINE: usize = 12;
    for chunk in bytes.chunks(PER_LINE) {
        s.push_str("    ");
        for b in chunk {
            s.push_str(&format!("0x{b:02x}, "));
        }
        // Drop the trailing space so rustfmt doesn't complain.
        s.truncate(s.trim_end_matches(' ').len());
        s.push('\n');
    }
    s.push_str("];\n");
    s
}
